# Step 1: Build the Next.js application using a Node.js base image
FROM node:16-alpine as builder

# Set the working directory
WORKDIR /app

# Install dependencies necessary for building the application
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of your application code
COPY . .

# Build your Next.js application
RUN npm run build

# Step 2: Use a smaller base image to reduce the final image size
FROM node:16-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json for installing production dependencies
COPY package.json package-lock.json ./

# Install only production dependencies
RUN npm install --production

# Copy the built Next.js application from the builder stage
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public

# Copy any other directories or files you specifically need for running the application
# For example, if you have a `locales` directory for i18n, copy it as well:
# COPY --from=builder /app/locales ./locales

# Specify the PORT environment variable, Google Cloud Run will set this value
ENV PORT 8080

# Ensure the application runs on the correct port
ENV NEXT_TELEMETRY_DISABLED 1

# Command to run your application
CMD ["npm", "start"]
